### ISSUE TITLE
How to stream to microcontroller with attached led panels?

### ISSUE THREAD

**Issue by ReinVelt** [psy0rz/ledder#3]
Documentation does not tell me how to stream data from ledder server to an attached microcontroller with led panels.
I have the ledder server working, that was easy. But now i need a microcontroller with firmware that works with ledder.
Which firmware or protocol do i need to install on the microcontroller?
Can you give me some hints?

**Comment by psy0rz** [comment]
yes this needs some work. you can use an esp32 with ledstream:

https://github.com/psy0rz/ledstream/tree/idf

(the esp-idf version)

Ill add some more documentation and a better example config in ledder

**Comment by psy0rz** [comment]
ive added some docs on ledstream, and updated displayconf-example.js

the DisplayQOISudp class should be used with ledstream.
